// user.enum.ts
// enums have been generated in schemas
import { registerEnumType } from '@nestjs/graphql';

// Enums from schema.prisma
export enum UserType {
  CREATOR = 'CREATOR',
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum GenderType {
  BOYS = 'BOYS',
  GIRLS = 'GIRLS',
  OTHERS = 'OTHERS',
}

export enum ToolType {
  IO = 'IO',
  CURD = 'CURD',
  IO_TEXT_TO_IMAGE = 'IO_TEXT_TO_IMAGE',
}

export enum ToolStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
}

export enum VisibilityType {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}

export enum PricingType {
  FREE = 'FREE',
  FREEMIUM = 'FREEMIUM',
  PAID = 'PAID',
  CUSTOM = 'CUSTOM',
  TRIAL = 'TRIAL',
}

export enum ListedBy {
  GEMENAI = 'GEMENAI',
  USER = 'USER',
  GPT = 'GPT',
}

export enum AiType {
  GENERATIVE_AI = 'GENERATIVE_AI',
  CONVERSATIONAL_AI = 'CONVERSATIONAL_AI',
  COMPUTER_VISION = 'COMPUTER_VISION',
  SPEECH_AI = 'SPEECH_AI',
  RECOMMENDATION_AI = 'RECOMMENDATION_AI',
  AUTOMATION_AI = 'AUTOMATION_AI',
  ANALYTICS_AI = 'ANALYTICS_AI',
  SEARCH_RETRIEVAL_AI = 'SEARCH_RETRIEVAL_AI',
  CODE_AI = 'CODE_AI',
  MARKETING_AI = 'MARKETING_AI',
  SECURITY_AI = 'SECURITY_AI',
  // AI_AGENT = 'AI_AGENT',
  OTHER = 'OTHER',
}

export enum ProductType {
  APPLICATION = 'APPLICATION',
  MODEL = 'MODEL',
  DATASET = 'DATASET',
  AGENT = 'AGENT',
  FRAMEWORK = 'FRAMEWORK',
  TOOLKIT = 'TOOLKIT',
  TEMPLATE = 'TEMPLATE',
  SERVICE = 'SERVICE',
  HARDWARE = 'HARDWARE',
  OTHER = 'OTHER',
}

export enum AiCapability {
  FOUNDATION_MODEL = 'FOUNDATION_MODEL',
  GENERATIVE_TEXT = 'GENERATIVE_TEXT',
  GENERATIVE_IMAGE = 'GENERATIVE_IMAGE',
  GENERATIVE_AUDIO = 'GENERATIVE_AUDIO',
  GENERATIVE_VIDEO = 'GENERATIVE_VIDEO',
  MULTIMODAL_UNDERSTANDING = 'MULTIMODAL_UNDERSTANDING',
  NLP_UNDERSTANDING = 'NLP_UNDERSTANDING',
  SEARCH_RETRIEVAL = 'SEARCH_RETRIEVAL',
  KNOWLEDGE_AI = 'KNOWLEDGE_AI',
  COMPUTER_VISION = 'COMPUTER_VISION',
  OCR_DOCUMENT_AI = 'OCR_DOCUMENT_AI',
  SPEECH_ASR = 'SPEECH_ASR',
  SPEECH_TTS = 'SPEECH_TTS',
  SPEAKER_TECH = 'SPEAKER_TECH',
  RECOMMENDATION = 'RECOMMENDATION',
  TIME_SERIES_FORECASTING = 'TIME_SERIES_FORECASTING',
  OPTIMIZATION_PLANNING = 'OPTIMIZATION_PLANNING',
  ANOMALY_DETECTION = 'ANOMALY_DETECTION',
  CAUSAL_INFERENCE = 'CAUSAL_INFERENCE',
  ANALYTICS_BI = 'ANALYTICS_BI',
  CODE_AI = 'CODE_AI',
  SECURITY_ML = 'SECURITY_ML',
  PRIVACY_PRESERVING_ML = 'PRIVACY_PRESERVING_ML',
  MLOPS_OBSERVABILITY = 'MLOPS_OBSERVABILITY',
  SYNTHETIC_DATA = 'SYNTHETIC_DATA',
  ROBOTICS_CONTROL = 'ROBOTICS_CONTROL',
  EDGE_AI = 'EDGE_AI',
  OTHER = 'OTHER',
}

export enum Domain {
  MARKETING = 'MARKETING',
  DEVELOPMENT = 'DEVELOPMENT',
  BUSINESS = 'BUSINESS',
  DESIGN = 'DESIGN',
  FINANCE = 'FINANCE',
  HEALTHCARE = 'HEALTHCARE',
  EDUCATION = 'EDUCATION',
  PRODUCTIVITY = 'PRODUCTIVITY',
  RESEARCH = 'RESEARCH',
  LEGAL = 'LEGAL',
  ENTERTAINMENT = 'ENTERTAINMENT',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  SALES = 'SALES',
  DATA_ANALYTICS = 'DATA_ANALYTICS',
  HUMAN_RESOURCES = 'HUMAN_RESOURCES',
  SECURITY = 'SECURITY',
  OPERATIONS = 'OPERATIONS',
  CONTENT_CREATION = 'CONTENT_CREATION',
  ECOMMERCE = 'ECOMMERCE',
  GAMING = 'GAMING',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  VIDEO_CREATION = 'VIDEO_CREATION',
  AUDIO_MUSIC = 'AUDIO_MUSIC',
  WRITING = 'WRITING',
  TRANSLATION = 'TRANSLATION',
  IMAGE_GENERATION = 'IMAGE_GENERATION',
  VIRTUAL_ASSISTANT = 'VIRTUAL_ASSISTANT',
  AUTOMATION = 'AUTOMATION',
  CHATBOT = 'CHATBOT',
  CLOUD = 'CLOUD',
  AGRICULTURE = 'AGRICULTURE',
  MANUFACTURING = 'MANUFACTURING',
  OTHER = 'OTHER',
}

export enum Modality {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  AUDIO = 'AUDIO',
  VIDEO = 'VIDEO',
  TABULAR = 'TABULAR',
  TIME_SERIES = 'TIME_SERIES',

  GRAPH = 'GRAPH',
  THREE_D = 'THREE_D',
  MULTIMODAL = 'MULTIMODAL',
  SENSOR_DATA = 'SENSOR_DATA',
  GEOSPATIAL = 'GEOSPATIAL',
}

export enum Delivery {
  SAAS = 'SAAS',
  API = 'API',
  SDK = 'SDK',
  MODEL_WEIGHTS = 'MODEL_WEIGHTS',
  OPEN_SOURCE = 'OPEN_SOURCE',
  ON_PREM = 'ON_PREM',
  EDGE_DEVICE = 'EDGE_DEVICE',
  MARKETPLACE_PLUGIN = 'MARKETPLACE_PLUGIN',
}

export enum PlatformType {
  WEB = 'WEB',
  MOBILE = 'MOBILE',
  DESKTOP = 'DESKTOP',
  API = 'API',
  SDK = 'SDK',
  WEBHOOK = 'WEBHOOK',
  PLUGIN = 'PLUGIN',
  EXTENSION = 'EXTENSION',
  OTHER = 'OTHER',
}

export enum IntegrationOption {
  ZAPIER = 'ZAPIER',
  INTEGROMAT = 'INTEGROMAT',
  SLACK = 'SLACK',
  MICROSOFT_TEAMS = 'MICROSOFT_TEAMS',
  GOOGLE_WORKSPACE = 'GOOGLE_WORKSPACE',
  NOTION = 'NOTION',
  FIGMA = 'FIGMA',
  SHOPIFY = 'SHOPIFY',
  WORDPRESS = 'WORDPRESS',
  SALESFORCE = 'SALESFORCE',
  HUBSPOT = 'HUBSPOT',
  CLOUD_DRIVE = 'CLOUD_DRIVE',
  IDE_PLUGIN = 'IDE_PLUGIN',
  CRM = 'CRM',
  DATABASE = 'DATABASE',
  API_CONNECTOR = 'API_CONNECTOR',
  OTHER = 'OTHER',
}

export enum ToolUserType {
  DEVELOPER = 'DEVELOPER',
  SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
  MACHINE_LEARNING_ENGINEER = 'MACHINE_LEARNING_ENGINEER',
  DATA_SCIENTIST = 'DATA_SCIENTIST',
  AI_RESEARCHER = 'AI_RESEARCHER',
  IT_PROFESSIONAL = 'IT_PROFESSIONAL',
  CLOUD_ENGINEER = 'CLOUD_ENGINEER',
  DEVOPS_ENGINEER = 'DEVOPS_ENGINEER',
  CYBERSECURITY_SPECIALIST = 'CYBERSECURITY_SPECIALIST',
  QA_ENGINEER = 'QA_ENGINEER',
  // --- Business & Management ---
  ENTREPRENEUR = 'ENTREPRENEUR',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  PRODUCT_MANAGER = 'PRODUCT_MANAGER',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  BUSINESS_ANALYST = 'BUSINESS_ANALYST',
  CONSULTANT = 'CONSULTANT',
  SALES_PROFESSIONAL = 'SALES_PROFESSIONAL',
  CUSTOMER_SUPPORT_AGENT = 'CUSTOMER_SUPPORT_AGENT',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  STRATEGY_PLANNER = 'STRATEGY_PLANNER',
  // --- Marketing & Growth ---
  MARKETER = 'MARKETER',
  DIGITAL_MARKETER = 'DIGITAL_MARKETER',
  SEO_SPECIALIST = 'SEO_SPECIALIST',
  SOCIAL_MEDIA_MANAGER = 'SOCIAL_MEDIA_MANAGER',
  BRAND_MANAGER = 'BRAND_MANAGER',
  ADVERTISING_SPECIALIST = 'ADVERTISING_SPECIALIST',
  // --- Creative & Media ---
  DESIGNER = 'DESIGNER',
  GRAPHIC_DESIGNER = 'GRAPHIC_DESIGNER',
  UX_UI_DESIGNER = 'UX_UI_DESIGNER',
  VIDEO_EDITOR = 'VIDEO_EDITOR',
  CONTENT_CREATOR = 'CONTENT_CREATOR',
  WRITER = 'WRITER',
  COPYWRITER = 'COPYWRITER',
  MUSIC_PRODUCER = 'MUSIC_PRODUCER',
  ANIMATOR = 'ANIMATOR',
  // --- Education & Research ---
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
  TRAINER = 'TRAINER',
  RESEARCHER = 'RESEARCHER',
  EDUCATOR = 'EDUCATOR',
  // --- Specialized Professions ---
  HEALTHCARE_PROFESSIONAL = 'HEALTHCARE_PROFESSIONAL',
  LEGAL_PROFESSIONAL = 'LEGAL_PROFESSIONAL',
  FINANCE_PROFESSIONAL = 'FINANCE_PROFESSIONAL',
  HR_PROFESSIONAL = 'HR_PROFESSIONAL',
  // --- General & Others ---
  GAMER = 'GAMER',
  HOBBYIST = 'HOBBYIST',
  OTHER = 'OTHER',
}

// Register GraphQL enum types
registerEnumType(UserType, {
  name: 'UserType',
});

registerEnumType(ToolUserType, {
  name: 'ToolUserType',
});

registerEnumType(PricingType, {
  name: 'PricingType',
});

registerEnumType(AiType, {
  name: 'AiType',
});

registerEnumType(ProductType, {
  name: 'ProductType',
});

registerEnumType(AiCapability, {
  name: 'AiCapability',
});

registerEnumType(Domain, {
  name: 'Domain',
});

registerEnumType(Modality, {
  name: 'Modality',
});

registerEnumType(Delivery, {
  name: 'Delivery',
});

registerEnumType(PlatformType, {
  name: 'PlatformType',
});

registerEnumType(IntegrationOption, {
  name: 'IntegrationOption',
});

registerEnumType(GenderType, {
  name: 'GenderType',
});

registerEnumType(ToolType, {
  name: 'ToolType',
});

registerEnumType(ToolStatus, {
  name: 'ToolStatus',
});

registerEnumType(VisibilityType, {
  name: 'VisibilityType',
});

registerEnumType(ListedBy, {
  name: 'ListedBy',
});

// Legacy enums for backward compatibility
export enum Gender {
  BOYS = 'BOYS',
  GIRLS = 'GIRLS',
  OTHERS = 'OTHERS',
}

registerEnumType(Gender, {
  name: 'Gender',
});

export enum Priority {
  HIGH = 'HIGH',
  MID = 'MID',
  LOW = 'LOW',
}

registerEnumType(Priority, {
  name: 'Priority',
});
