name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3 
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build Nest.js app
      run: npm run build

    - name: Stop and start application with PM2
      run: |
        pm2 resurrect || true  # Resurrect previously running processes, ignore errors
        pm2 start 0 --update-env  # Start the application with PM2

    - name: Save pm2
      run: pm2 save

    - name: Restart nginx
      run: sudo service nginx restart
