name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3 
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    # Uncomment the next three lines if pm2 is not installed globally
    # - name: Install pm2 globally
    #   run: npm install -g pm2

    - name: Copy .env.example to .env
      run: cp .env.example .env

    # - name: Build Nest.js app (If necessary)
    #   run: npm run build

    - name: Stop and start application with PM2
      run: |
        # Resurrect PM2 processes
        pm2 resurrect || true

        # Start the application with PM2
        pm2 start 0 --update-env

    - name: Save pm2
      run: pm2 save

    - name: Restart nginx
      run: sudo service nginx restart
